flowchart TB
  N4(jinja2) --> N9(markupsafe)
  N0(flask) --> N3(itsdangerous)
  N0(flask) --> N5(werkzeug)
  N0(flask) --> N1(click)
  N0(flask) --> N2(importlib-metadata)
  N0(flask) --> N4(jinja2)
  N1(click) --> N6(colorama)
  N1(click) --> N2(importlib-metadata)
  N2(importlib-metadata) --> N7(typing-extensions)
  N2(importlib-metadata) --> N8(zipp)

